detail:
  replicaCount: 2
  namespace: apps
  name: backend-service
  serviceAccount: backend-service
  image:
    pullPolicy: Always
  service:
    type: ClusterIP
    targetPort: 3000

canaryConfig:
  - name: "backend-v1"
    tag: "v1.0.0"
    weight: 50
  - name: "backend-v6"
    tag: "v6.0.0"
    weight: 50